version: '2'

services:
  tensorflow-serving:
    container_name: 'model-image_caption'
    image: 'bitnami/tensorflow-serving:latest'
    ports:
    - '8500:8500'
    volumes:
    - '/media/tabul/DATA/GLAIR-interns/2018/aditya-alif-nugraha/models/serving_model:/bitnami'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  frontend:
    container_name: 'frontend-image_caption'
    build: 'frontend/'
    ports:
    - '5000:5000'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  backend:
    container_name: 'backend-image_caption'
    build: 'backend/'
    ports:
    - '5050:5050'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1
