name: image-caption

dependencies:
  - python=3.6
  - pip=19.0.1
  - pip:
      - tensorflow
      - h5py
      - keras
      - jupyter
      - pillow
      - matplotlib
      - nltk
      - opencv-python
      - flask
      - requests
      - tensorflow-serving-api
      - docker
